-- -- This script was generated by the ERD tool in pgAdmin 4.
-- -- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
-- BEGIN;


-- CREATE TABLE IF NOT EXISTS public.investor
-- (
--     id serial NOT NULL,
--     id_investor text COLLATE pg_catalog."default" NOT NULL,
--     key_id character varying COLLATE pg_catalog."default" NOT NULL,
--     public_key character varying COLLATE pg_catalog."default" NOT NULL,
--     date_creation timestamp without time zone NOT NULL DEFAULT now(),
--     date_update timestamp without time zone NOT NULL DEFAULT now(),
--     CONSTRAINT "PK_c60a173349549955c39d3703551" PRIMARY KEY (id),
--     CONSTRAINT "UQ_68db5892488ba832448e2160a13" UNIQUE (id_investor),
--     CONSTRAINT "UQ_6addff55c8ad2872224f191d81a" UNIQUE (public_key)
-- );

-- CREATE TABLE IF NOT EXISTS public.offer
-- (
--     id serial NOT NULL,
--     id_offer text COLLATE pg_catalog."default" NOT NULL,
--     name character varying COLLATE pg_catalog."default" NOT NULL,
--     symbol character varying COLLATE pg_catalog."default" NOT NULL,
--     decimals smallint NOT NULL,
--     total_supply numeric NOT NULL,
--     contract_hash character varying COLLATE pg_catalog."default" NOT NULL,
--     date_creation timestamp without time zone NOT NULL DEFAULT now(),
--     date_update timestamp without time zone NOT NULL DEFAULT now(),
--     CONSTRAINT "PK_57c6ae1abe49201919ef68de900" PRIMARY KEY (id),
--     CONSTRAINT "UQ_6cf3f1b9007268b8862bc618b76" UNIQUE (symbol),
--     CONSTRAINT "UQ_c76a924c4da04f8e0bf5395e7cb" UNIQUE (contract_hash),
--     CONSTRAINT "UQ_cbeaf7aa0cb723b8d978a05d7b2" UNIQUE (name),
--     CONSTRAINT "UQ_d1f613d259716251028f416d800" UNIQUE (id_offer)
-- );

-- CREATE TABLE IF NOT EXISTS public.offer_investor
-- (
--     id serial NOT NULL,
--     date_creation timestamp without time zone NOT NULL DEFAULT now(),
--     date_update timestamp without time zone NOT NULL DEFAULT now(),
--     "investorId" integer,
--     "offerId" integer,
--     CONSTRAINT "PK_dcd22293f2c86cc8c8b264c22ff" PRIMARY KEY ("investorId", "offerId")
-- );

-- CREATE TABLE IF NOT EXISTS public.offer_sponsor
-- (
--     id serial NOT NULL,
--     date_creation timestamp without time zone NOT NULL DEFAULT now(),
--     date_update timestamp without time zone NOT NULL DEFAULT now(),
--     "sponsorId" integer NOT NULL,
--     "offerId" integer NOT NULL,
--     CONSTRAINT "PK_2f9150347e39fcf438c54574d33" PRIMARY KEY ("sponsorId", "offerId")
-- );

-- CREATE TABLE IF NOT EXISTS public.sponsor
-- (
--     id serial NOT NULL,
--     id_sponsor text COLLATE pg_catalog."default" NOT NULL,
--     key_id character varying COLLATE pg_catalog."default" NOT NULL,
--     public_key character varying COLLATE pg_catalog."default" NOT NULL,
--     date_creation timestamp without time zone NOT NULL DEFAULT now(),
--     date_update timestamp without time zone NOT NULL DEFAULT now(),
--     CONSTRAINT "PK_31c4354cde945c685aabe017541" PRIMARY KEY (id),
--     CONSTRAINT "UQ_774b4fcf5397219951454c91b3f" UNIQUE (id_sponsor),
--     CONSTRAINT "UQ_ddc54a5fbcbd1a172ec9fb16a97" UNIQUE (public_key)
-- );

-- ALTER TABLE IF EXISTS public.offer_investor
--     ADD CONSTRAINT "FK_06ab41a05037b47a4d9714ef7d7" FOREIGN KEY ("investorId")
--     REFERENCES public.investor (id) MATCH SIMPLE
--     ON UPDATE CASCADE
--     ON DELETE CASCADE;
-- CREATE INDEX IF NOT EXISTS "IDX_06ab41a05037b47a4d9714ef7d"
--     ON public.offer_investor("investorId");


-- ALTER TABLE IF EXISTS public.offer_investor
--     ADD CONSTRAINT "FK_36398a4d1c5b1aff8fde1354fce" FOREIGN KEY ("offerId")
--     REFERENCES public.offer (id) MATCH SIMPLE
--     ON UPDATE NO ACTION
--     ON DELETE NO ACTION;
-- CREATE INDEX IF NOT EXISTS "IDX_36398a4d1c5b1aff8fde1354fc"
--     ON public.offer_investor("offerId");


-- ALTER TABLE IF EXISTS public.offer_sponsor
--     ADD CONSTRAINT "FK_1121031fe9507ec110ef8222fc2" FOREIGN KEY ("offerId")
--     REFERENCES public.offer (id) MATCH SIMPLE
--     ON UPDATE NO ACTION
--     ON DELETE NO ACTION;
-- CREATE INDEX IF NOT EXISTS "IDX_1121031fe9507ec110ef8222fc"
--     ON public.offer_sponsor("offerId");


-- ALTER TABLE IF EXISTS public.offer_sponsor
--     ADD CONSTRAINT "FK_a66a731eab3f56705ea4bbd3158" FOREIGN KEY ("sponsorId")
--     REFERENCES public.sponsor (id) MATCH SIMPLE
--     ON UPDATE CASCADE
--     ON DELETE CASCADE;
-- CREATE INDEX IF NOT EXISTS "IDX_a66a731eab3f56705ea4bbd315"
--     ON public.offer_sponsor("sponsorId");

-- END;